services:
  - mongodb

language: node_js
node_js:
  - "4.2.1"

before_install: npm install -g grunt-cli

install:
 - npm install

before_script:
  - sleep 15

branches:
  only:
    - master
    - develop

